//--- ATM		
#define IDC_ATM_TITLE								1238
#define IDC_ATM_TEXT_CASHSTR						1239
#define IDC_ATM_TEXT_BANKSTR						1240
#define IDC_ATM_TEXT_AMOUNTSTR						1241
#define IDC_ATM_TEXT_ACCOUNTNUMBER					1242
#define IDC_ATM_TEXT_CASHNUMBER						1243
#define IDC_ATM_BACKGROUND							1438
#define IDC_ATM_HEADER								1439
#define IDC_ATM_EDIT_AMOUNT							1638
#define IDC_ATM_BUTTON_WITHDRAW						1838
#define IDC_ATM_BUTTON_TRANSFER						1839
#define IDC_ATM_BUTTON_DEPOSIT						1840
#define IDC_ATM_COMBO_PLAYERS						2338
		
//--- PlayerMenu		
#define IDC_PLAYERMENU_TITLE						5741
#define IDC_PLAYERMENU_TEXTWEIGHT					5742
#define IDC_PLAYERMENU_BACKGROUND					5941
#define IDC_PLAYERMENU_HEADER						5942
#define IDC_PLAYERMENU_EDITUSE						6141
#define IDC_PLAYERMENU_EDITGIVE						6142
#define IDC_PLAYERMENU_LISTINVENTORY				6241
#define IDC_PLAYERMENU_LISTMENU						6242
#define IDC_PLAYERMENU_LISTPLAYERS					6243
#define IDC_PLAYERMENU_BUTTONUSE					6341
#define IDC_PLAYERMENU_BUTTONDROP					6342
#define IDC_PLAYERMENU_BUTTONGIVE					6343
#define IDC_PLAYERMENU_BUTTONCLOSE					6344
		
//--- ShopInfo		
#define IDC_SHOPINFO_TITLE							3893
#define IDC_SHOPINFO_STRTEXT						3993
#define IDC_SHOPINFO_BACKGROUND						4093
#define IDC_SHOPINFO_HEADER							4094
#define IDC_SHOPINFO_LISTMENU						4393
#define IDC_SHOPINFO_BUTTONCLOSE					4493
		
//--- Shop		
#define IDC_SHOP_TEXTAMOUNT							1662
#define IDC_SHOP_TEXTTITLE							1663
#define IDC_SHOP_TEXTSTRDESC						1762
#define IDC_SHOP_BACKGROUND							1862
#define IDC_SHOP_HEADER								1863
#define IDC_SHOP_EDITBOX							2062
#define IDC_SHOP_LISTSHOPITEMS						2162
#define IDC_SHOP_LISTINVITEMS						2163
#define IDC_SHOP_BUTTONBUY							2262
#define IDC_SHOP_BUTTONSELL							2263
#define IDC_SHOP_BUTTONCLOSE						2264

//--- MessageSystem
#define IDC_MESSAGESYSTEM_TITLE						7001
#define IDC_MESSAGESYSTEM_BACKGROUND				7202
#define IDC_MESSAGESYSTEM_HEADER					7201
#define IDC_MESSAGESYSTEM_EDITBOX					7401
#define IDC_MESSAGESYSTEM_BUTTONCLOSE				9948
#define IDC_MESSAGESYSTEM_BUTTONSEND				7601
			
		
//--- VehicleInteraction		
#define IDC_VEHICLEINTERACTION_TITLE				17161
#define IDC_VEHICLEINTERACTION_BUTTONCLOSE			17162
#define IDC_VEHICLEINTERACTION_BACKGROUND			17361
#define IDC_VEHICLEINTERACTION_HEADER				17362
#define IDC_VEHICLEINTERACTION_LISTMENU				17661
#define IDC_VEHICLEINTERACTION_LISTDISPLAY			17662
#define IDC_VEHICLEINTERACTION_BUTTON				17761

//--- Trunk
#define IDC_TRUNK_TEXTWEIGHT						2106
#define IDC_TRUNK_TITLE								2107
#define IDC_TRUNK_BACKGROUND						2306
#define IDC_TRUNK_HEADER							2307
#define IDC_TRUNK_EDIT								2506
#define IDC_TRUNK_LISTINVENTORY						2606
#define IDC_TRUNK_LISTTRUNK							2607
#define IDC_TRUNK_BUTTONSTORE						2706
#define IDC_TRUNK_BUTTONTAKE						2707
#define IDC_TRUNK_BUTTONCLOSE						2708

//--- TicketMenu
#define IDC_TICKETMENU_TITLE						5710
#define IDC_TICKETMENU_TEXTAMOUNT					5711
#define IDC_TICKETMENU_TEXTREASON					5712
#define IDC_TICKETMENU_BACKGROUND					5910
#define IDC_TICKETMENU_HEADER						5911
#define IDC_TICKETMENU_EDITAMOUNT					6110
#define IDC_TICKETMENU_EDITREASON					6111
#define IDC_TICKETMENU_BUTTONCLOSE					6310
#define IDC_TICKETMENU_BUTTONISSUE					6311


//--- QuestionMenu
#define IDC_QUESTIONMENU_TITLE						8001
#define IDC_QUESTIONMENU_STRUCTUREDTEXT				8101
#define IDC_QUESTIONMENU_BACKGROUND					8201
#define IDC_QUESTIONMENU_HEADER						8202
#define IDC_QUESTIONMENU_BUTTONACCEPT				8601
#define IDC_QUESTIONMENU_BUTTONDECLINE				8602
#define IDC_QUESTIONMENU_BUTTONCLOSE				8603

//--- InteractionMenu
#define IDC_INTERACTIONMENU_TITLE					12058
#define IDC_INTERACTIONMENU_BACKGROUND				12258
#define IDC_INTERACTIONMENU_HEADER					12259
#define IDC_INTERACTIONMENU_LISTDISPLAY				12558
#define IDC_INTERACTIONMENU_BUTTONCLOSE				12658
#define IDC_INTERACTIONMENU_COMBOACTIONS			13158

//--- Phone
#define IDC_PHONE_TITLE								2060
#define IDC_PHONE_BACKGROUND						2260
#define IDC_PHONE_HEADER							2261
#define IDC_PHONE_EDIT								2460
#define IDC_PHONE_LIST								2560
#define IDC_PHONE_BUTTONSEND						2660
#define IDC_PHONE_BUTTONCLOSE						2661

//--- UI
#define IDC_UI_VERSIONTEXT							1073
#define IDC_UI_TEXTBOX								1173
#define IDC_UI_BACKGROUND							1273
#define IDC_UI_RSCPICTURE_1201						1274
#define IDC_UI_TRANSPARENTICON						1275
